export const CREATE_USER = 'CREATE_USER'
export const CREATE_USERS = 'CREATE_USERS'
export const UPDATE_USER = 'UPDATE_USER'
export const UPDATE_USERS = 'UPDATE_USERS'
export const DELETE_USER = 'DELETE_USER'
